PostgreSQL:
  image: registry.gitlab.com/daamien/postgresql_anonymizer 
  ports:
    - "54322:5432"
  environment:
    - POSTGRES_PASSWORD=CHANGEME
  volumes:
    - $PWD:/tmp/source 
    - $PWD/anon:/usr/share/postgresql/10/extension/anon
